import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import { BrandSignatureBlock } from "@/components/BrandSignatureBlock";
import { AppFooter } from "@/components/AppFooter";

interface Props {
  params: Promise<{ token: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { token } = await params;
  const supabase = await createClient();
  const { data: job } = await supabase
    .from("jobs")
    .select("title, selected_family")
    .eq("share_token", token)
    .single();

  if (!job) return { title: "Shared Part — AI4U Little Engineer" };

  return {
    title: `${job.title} — AI4U Little Engineer`,
    description: `View this ${job.selected_family?.replace(/_/g, " ") ?? "part"} generated by AI4U Little Engineer.`,
  };
}

export default async function SharedJobPage({ params }: Props) {
  const { token } = await params;
  const supabase = await createClient();

  const { data: job, error } = await supabase
    .from("jobs")
    .select("*, part_specs(*), cad_runs(*), artifacts(*)")
    .eq("share_token", token)
    .single();

  if (error || !job) notFound();

  const latestSpec = Array.isArray(job.part_specs)
    ? job.part_specs.sort(
        (a: { version: number }, b: { version: number }) => b.version - a.version
      )[0]
    : null;

  const latestRun = Array.isArray(job.cad_runs)
    ? job.cad_runs.sort(
        (a: { created_at: string }, b: { created_at: string }) =>
          new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
      )[0]
    : null;

  const stlArtifact = Array.isArray(job.artifacts)
    ? job.artifacts.find((a: { kind: string }) => a.kind === "stl")
    : null;

  const stepArtifact = Array.isArray(job.artifacts)
    ? job.artifacts.find((a: { kind: string }) => a.kind === "step")
    : null;

  return (
    <div className="min-h-screen bg-steel-900">
      {/* Header */}
      <header className="border-b border-steel-800 px-4 sm:px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-brand-600 rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-sm">AI</span>
          </div>
          <span className="font-semibold text-steel-100">Little Engineer</span>
        </div>
        <Link href="/" className="btn-secondary text-sm py-1.5 px-4">
          Try AI4U Free
        </Link>
      </header>

      <main className="max-w-2xl mx-auto px-4 py-8 space-y-6">
        {/* Shared badge */}
        <div className="flex items-center gap-2 text-xs text-steel-500">
          <span>🔗</span>
          <span>Shared part — view only</span>
        </div>

        {/* Job header */}
        <div className="card">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold text-steel-100">{job.title}</h1>
              {job.selected_family && (
                <p className="text-steel-400 mt-1 capitalize">
                  {job.selected_family.replace(/_/g, " ")}
                </p>
              )}
            </div>
            <span
              className={`text-xs px-3 py-1 rounded-full flex-shrink-0 ${
                job.status === "printed"
                  ? "bg-teal-100 text-teal-700"
                  : job.status === "approved"
                  ? "bg-green-100 text-green-700"
                  : "bg-gray-100 text-gray-700"
              }`}
            >
              {job.status.replace(/_/g, " ")}
            </span>
          </div>
          <div className="mt-4 text-xs text-steel-500">
            Generated{" "}
            {new Date(job.created_at).toLocaleDateString("en-US", {
              month: "long",
              day: "numeric",
              year: "numeric",
            })}
          </div>
        </div>

        {/* Spec summary */}
        {latestSpec && (
          <div className="card">
            <h2 className="font-semibold text-steel-200 mb-3">Part Specification</h2>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <span className="text-steel-500">Family</span>
                <p className="text-steel-200 capitalize">
                  {latestSpec.family?.replace(/_/g, " ") ?? "—"}
                </p>
              </div>
              <div>
                <span className="text-steel-500">Units</span>
                <p className="text-steel-200 uppercase">{latestSpec.units ?? "—"}</p>
              </div>
              {latestSpec.material && (
                <div>
                  <span className="text-steel-500">Material</span>
                  <p className="text-steel-200">{latestSpec.material}</p>
                </div>
              )}
              {job.confidence_score && (
                <div>
                  <span className="text-steel-500">AI Confidence</span>
                  <p className="text-steel-200">
                    {Math.round(job.confidence_score * 100)}%
                  </p>
                </div>
              )}
            </div>
            {latestSpec.dimensions_json &&
              Object.keys(latestSpec.dimensions_json).length > 0 && (
                <div className="mt-4">
                  <span className="text-steel-500 text-sm">Dimensions</span>
                  <div className="mt-2 grid grid-cols-2 gap-2">
                    {Object.entries(
                      latestSpec.dimensions_json as Record<string, unknown>
                    ).map(([k, v]) => (
                      <div key={k} className="text-xs">
                        <span className="text-steel-500 capitalize">
                          {k.replace(/_/g, " ")}:
                        </span>{" "}
                        <span className="text-steel-300">{String(v)}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
          </div>
        )}

        {/* CAD run info */}
        {latestRun && (
          <div className="card">
            <h2 className="font-semibold text-steel-200 mb-3">CAD Generation</h2>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <span className="text-steel-500">Engine</span>
                <p className="text-steel-200 uppercase">{latestRun.engine}</p>
              </div>
              <div>
                <span className="text-steel-500">Generator</span>
                <p className="text-steel-200">{latestRun.generator_name}</p>
              </div>
              <div>
                <span className="text-steel-500">Status</span>
                <p className="text-steel-200 capitalize">{latestRun.status}</p>
              </div>
              {latestRun.generator_version && (
                <div>
                  <span className="text-steel-500">Version</span>
                  <p className="text-steel-200">{latestRun.generator_version}</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Download buttons */}
        {(stlArtifact || stepArtifact) && (
          <div className="card">
            <h2 className="font-semibold text-steel-200 mb-3">Download Files</h2>
            <div className="flex flex-wrap gap-3">
              {stlArtifact && (
                <a
                  href={`/api/artifacts/${stlArtifact.id}/download`}
                  className="btn-primary text-sm py-2 px-4 flex items-center gap-2"
                >
                  <span>⬇️</span>
                  Download STL
                </a>
              )}
              {stepArtifact && (
                <a
                  href={`/api/artifacts/${stepArtifact.id}/download`}
                  className="btn-secondary text-sm py-2 px-4 flex items-center gap-2"
                >
                  <span>⬇️</span>
                  Download STEP
                </a>
              )}
            </div>
            <p className="text-xs text-steel-500 mt-3">
              Files are shared publicly by the owner. No login required.
            </p>
          </div>
        )}

        {/* Brand Signature */}
        <div className="card bg-steel-900/50 border-steel-800">
          <BrandSignatureBlock showTagline />
        </div>

        {/* CTA */}
        <div className="card bg-brand-900/30 border-brand-800 text-center py-8">
          <div className="text-3xl mb-3">🔧</div>
          <h3 className="text-lg font-semibold text-steel-100 mb-2">
            Generate your own parts
          </h3>
          <p className="text-steel-400 text-sm mb-4">
            AI4U Little Engineer turns plain English into production-ready CAD files
            in seconds. Free to start.
          </p>
          <Link href="/signup" className="btn-primary">
            Get Started Free
          </Link>
        </div>
      </main>
      <AppFooter />
    </div>
  );
}
