"use client";

/**
 * InventionProtectionPanel
 *
 * Invention Protection Mode — generates and displays a patent-ready
 * technical summary for a design.
 *
 * Features:
 *   - One-click generation via LLM
 *   - Structured display of all patent sections
 *   - Claims list with numbered formatting
 *   - Download as plain text or copy to clipboard
 *   - Timestamp and metadata footer
 *   - Copyright notice: © AI4U, LLC
 */

import { useState } from "react";

interface PatentSummary {
  title: string;
  field: string;
  background: string;
  summary: string;
  description: string;
  claims: string[];
  abstract: string;
  novelty_statement: string;
  prior_art_distinction: string;
  industrial_applicability: string;
  _metadata?: {
    job_id: string;
    generated_at: string;
    origin: string;
    platform: string;
    vpl_grade?: string | null;
    vpl_score?: number | null;
    copyright: string;
  };
}

interface InventionProtectionPanelProps {
  jobId: string;
  initialSummary?: PatentSummary | null;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <h4 className="text-xs font-semibold text-steel-400 uppercase tracking-wide">{title}</h4>
      <div className="text-sm text-steel-300 leading-relaxed">{children}</div>
    </div>
  );
}

export function InventionProtectionPanel({
  jobId,
  initialSummary = null,
}: InventionProtectionPanelProps) {
  const [summary, setSummary] = useState<PatentSummary | null>(initialSummary);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  async function generate(force = false) {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/jobs/${jobId}/patent-summary`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ force }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Generation failed");
      setSummary(data.summary);
      setExpanded(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate summary");
    } finally {
      setLoading(false);
    }
  }

  function buildPlainText(s: PatentSummary): string {
    const lines: string[] = [
      "PATENT-READY TECHNICAL SUMMARY",
      "Generated by AI4U Little Engineer — Invention Protection Mode",
      s._metadata?.copyright ?? "© AI4U, LLC. AI4Utech.com, Lee Hanna-Owner.",
      `Generated: ${s._metadata?.generated_at ? new Date(s._metadata.generated_at).toLocaleString() : "Unknown"}`,
      "",
      "═".repeat(60),
      "",
      `TITLE: ${s.title}`,
      "",
      "FIELD OF THE INVENTION",
      s.field,
      "",
      "BACKGROUND",
      s.background,
      "",
      "SUMMARY OF THE INVENTION",
      s.summary,
      "",
      "DETAILED DESCRIPTION",
      s.description,
      "",
      "CLAIMS",
      ...s.claims.map((c, i) => `${i + 1}. ${c}`),
      "",
      "ABSTRACT",
      s.abstract,
      "",
      "NOVELTY STATEMENT",
      s.novelty_statement,
      "",
      "DISTINCTION FROM PRIOR ART",
      s.prior_art_distinction,
      "",
      "INDUSTRIAL APPLICABILITY",
      s.industrial_applicability,
      "",
      "═".repeat(60),
      "METADATA",
      `Platform: ${s._metadata?.platform ?? "AI4U Little Engineer"}`,
      `Origin: ${s._metadata?.origin ?? "ai_generated"}`,
      `VPL Grade: ${s._metadata?.vpl_grade ?? "N/A"} | Score: ${s._metadata?.vpl_score ?? "N/A"}`,
    ];
    return lines.join("\n");
  }

  async function copyToClipboard() {
    if (!summary) return;
    await navigator.clipboard.writeText(buildPlainText(summary));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function downloadTxt() {
    if (!summary) return;
    const text = buildPlainText(summary);
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `patent-summary-${jobId.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="card border-indigo-800/40 bg-indigo-950/20 space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <svg className="w-5 h-5 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <div>
            <h3 className="font-semibold text-steel-100 text-sm">Invention Protection Mode</h3>
            <p className="text-xs text-steel-500">Generate a patent-ready technical summary</p>
          </div>
        </div>
        {summary && (
          <button
            onClick={() => setExpanded(!expanded)}
            className="text-xs text-steel-500 hover:text-steel-300 transition-colors"
          >
            {expanded ? "Collapse" : "Expand"}
          </button>
        )}
      </div>

      {/* Generate button */}
      {!summary ? (
        <div className="space-y-3">
          <p className="text-xs text-steel-400 leading-relaxed">
            Generate a structured patent-ready technical summary for this design. The document includes
            formal claims, detailed description, abstract, and novelty statement — suitable for use in
            a provisional patent application.
          </p>
          <button
            onClick={() => generate(false)}
            disabled={loading}
            className="w-full btn-secondary text-sm py-2.5 flex items-center justify-center gap-2 border-indigo-700/50 text-indigo-300 hover:text-indigo-200 hover:border-indigo-600"
          >
            {loading ? (
              <>
                <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Generating patent summary…
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Generate Patent Summary
              </>
            )}
          </button>
        </div>
      ) : (
        <>
          {/* Action buttons */}
          <div className="flex gap-2">
            <button
              onClick={copyToClipboard}
              className="flex-1 btn-secondary text-xs py-2 flex items-center justify-center gap-1.5"
            >
              {copied ? (
                <>
                  <svg className="w-3.5 h-3.5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                  Copied!
                </>
              ) : (
                <>
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  Copy Text
                </>
              )}
            </button>
            <button
              onClick={downloadTxt}
              className="flex-1 btn-secondary text-xs py-2 flex items-center justify-center gap-1.5"
            >
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Download .txt
            </button>
            <button
              onClick={() => generate(true)}
              disabled={loading}
              className="text-xs text-steel-500 hover:text-steel-300 transition-colors px-2"
              title="Regenerate"
            >
              {loading ? "…" : "↻"}
            </button>
          </div>

          {/* Summary content */}
          {expanded && (
            <div className="space-y-4 border-t border-steel-800 pt-4">
              <div className="bg-steel-800/40 rounded-lg px-4 py-3">
                <h3 className="font-bold text-steel-100 text-base">{summary.title}</h3>
              </div>

              <Section title="Abstract">{summary.abstract}</Section>
              <Section title="Field of the Invention">{summary.field}</Section>
              <Section title="Background">{summary.background}</Section>
              <Section title="Summary">{summary.summary}</Section>
              <Section title="Detailed Description">{summary.description}</Section>

              <Section title="Claims">
                <ol className="list-decimal list-inside space-y-2">
                  {summary.claims.map((claim, i) => (
                    <li key={i} className="text-steel-300 text-sm leading-relaxed">
                      {claim}
                    </li>
                  ))}
                </ol>
              </Section>

              <Section title="Novelty Statement">{summary.novelty_statement}</Section>
              <Section title="Distinction from Prior Art">{summary.prior_art_distinction}</Section>
              <Section title="Industrial Applicability">{summary.industrial_applicability}</Section>

              {/* Metadata footer */}
              {summary._metadata && (
                <div className="border-t border-steel-800 pt-3 space-y-1 text-xs text-steel-600">
                  <p>Generated: {new Date(summary._metadata.generated_at).toLocaleString()}</p>
                  <p>Platform: {summary._metadata.platform} · Origin: {summary._metadata.origin}</p>
                  {summary._metadata.vpl_grade && (
                    <p>VPL Grade: {summary._metadata.vpl_grade} · Score: {summary._metadata.vpl_score}/100</p>
                  )}
                  <p className="text-steel-700">{summary._metadata.copyright}</p>
                </div>
              )}
            </div>
          )}
        </>
      )}

      {error && (
        <p className="text-xs text-red-400 bg-red-900/20 border border-red-800 rounded px-3 py-2">
          {error}
        </p>
      )}
    </div>
  );
}

export default InventionProtectionPanel;
