import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use | AI4U Little Engineer",
  description:
    "Terms of Use for AI4U Little Engineer — the AI-powered 3D CAD design and marketplace platform.",
};

const EFFECTIVE_DATE = "April 1, 2026";
const COMPANY = "AI4U, LLC";
const OWNER = "Lee Hanna";
const WEBSITE = "AI4Utech.com";
const EMAIL = "legal@ai4utech.com";

export default function TermsOfUsePage() {
  return (
    <div className="min-h-screen bg-steel-900">
      {/* Header */}
      <header className="border-b border-steel-800 px-4 sm:px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-brand-600 rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-sm">AI</span>
          </div>
          <span className="font-semibold text-steel-100">Little Engineer</span>
        </div>
        <Link href="/" className="text-sm text-steel-400 hover:text-steel-200 transition-colors">
          ← Back to Home
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-10 space-y-8">
        {/* Title block */}
        <div className="space-y-2">
          <h1 className="text-3xl font-bold text-steel-100">Terms of Use</h1>
          <p className="text-steel-400 text-sm">
            Effective Date: {EFFECTIVE_DATE} &nbsp;·&nbsp; {COMPANY} &nbsp;·&nbsp; {OWNER}, Owner
          </p>
          <p className="text-steel-500 text-xs">
            © {COMPANY}. {WEBSITE}
          </p>
        </div>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-steel-300 leading-relaxed">

          {/* 1 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the AI4U Little Engineer platform (the &ldquo;Service&rdquo;), you agree to
              be bound by these Terms of Use (&ldquo;Terms&rdquo;). If you do not agree to these Terms, you may
              not use the Service. These Terms constitute a legally binding agreement between you and{" "}
              <strong className="text-steel-200">{COMPANY}</strong>, a limited liability company owned by{" "}
              <strong className="text-steel-200">{OWNER}</strong>.
            </p>
          </section>

          {/* 2 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">2. Description of Service</h2>
            <p>
              AI4U Little Engineer is an AI-powered platform that converts plain-English problem descriptions
              into 3D-printable CAD designs. The Service includes:
            </p>
            <ul className="list-disc list-inside space-y-1 text-steel-400">
              <li>Automated CAD generation using proprietary AI models</li>
              <li>Virtual Print Lab (VPL) quality validation and scoring</li>
              <li>Trust Policy Engine for design quality certification</li>
              <li>KeyGuardian security and secret management infrastructure</li>
              <li>A marketplace for buying and selling validated 3D designs</li>
              <li>AI-generated concept renders and usage images</li>
            </ul>
          </section>

          {/* 3 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">3. AI-Generated Content</h2>
            <p>
              All designs, CAD files, images, and text generated by the Service are produced by artificial
              intelligence systems. {COMPANY} makes no warranty that AI-generated designs are fit for any
              particular purpose, structurally sound, or safe for use without independent engineering review.
            </p>
            <p>
              <strong className="text-steel-200">You assume all risk</strong> associated with printing,
              manufacturing, or using any design generated by the Service. Always verify critical dimensions
              and structural integrity before use in load-bearing or safety-critical applications.
            </p>
            <p>
              Designs that have passed Virtual Print Lab (VPL) validation carry a quality score and grade,
              but this does not constitute a professional engineering certification.
            </p>
          </section>

          {/* 4 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">4. Intellectual Property</h2>
            <p>
              <strong className="text-steel-200">Your designs:</strong> You retain ownership of the problem
              descriptions you submit. For AI-generated output based on your inputs, you are granted a
              non-exclusive, worldwide license to use, reproduce, and distribute the generated designs for
              personal and commercial purposes, subject to these Terms.
            </p>
            <p>
              <strong className="text-steel-200">Platform IP:</strong> The Service, including the VPL engine,
              Trust Policy Engine, KeyGuardian system, all underlying software, algorithms, and brand assets,
              are the exclusive intellectual property of {COMPANY}. You may not reverse-engineer, copy,
              or create derivative works of any platform component.
            </p>
            <p>
              <strong className="text-steel-200">Marketplace designs:</strong> Purchased designs are licensed
              for personal and commercial use by the buyer. Resale or redistribution of purchased designs
              without modification is prohibited. See the{" "}
              <Link href="/marketplace/license" className="text-brand-400 hover:text-brand-300 underline">
                Marketplace License Terms
              </Link>{" "}
              for full details.
            </p>
          </section>

          {/* 5 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">5. User Conduct</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-1 text-steel-400">
              <li>Generate designs for weapons, illegal devices, or items intended to cause harm</li>
              <li>Circumvent or attempt to bypass VPL validation or Trust Policy gating</li>
              <li>Upload or submit content that infringes third-party intellectual property rights</li>
              <li>Scrape, crawl, or systematically extract data from the platform</li>
              <li>Attempt to access systems, accounts, or data not belonging to you</li>
              <li>Misrepresent the origin, quality, or validation status of any design</li>
            </ul>
          </section>

          {/* 6 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">6. Marketplace and Payments</h2>
            <p>
              The AI4U marketplace allows creators to sell validated designs to buyers. All transactions are
              processed through Stripe. {COMPANY} charges a platform fee on each sale as disclosed at
              checkout. All sales are final unless the design is materially misrepresented.
            </p>
            <p>
              Only designs that have achieved a &ldquo;Verified Commercial&rdquo; trust tier (VPL Grade A or B,
              score ≥ 75) are eligible for sale on the marketplace. This requirement exists to protect buyers
              and maintain platform quality.
            </p>
          </section>

          {/* 7 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">7. Disclaimers and Limitation of Liability</h2>
            <p>
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTY OF ANY KIND. {COMPANY.toUpperCase()}{" "}
              EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY,
              FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
            <p>
              IN NO EVENT SHALL {COMPANY.toUpperCase()} BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING DAMAGES
              FROM PRINTING OR USING AI-GENERATED DESIGNS.
            </p>
          </section>

          {/* 8 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">8. Privacy</h2>
            <p>
              Your use of the Service is also governed by our Privacy Policy. By using the Service, you
              consent to the collection and use of your information as described therein. We do not sell
              your personal data to third parties.
            </p>
          </section>

          {/* 9 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">9. Modifications to Terms</h2>
            <p>
              {COMPANY} reserves the right to modify these Terms at any time. We will notify registered
              users of material changes via email. Continued use of the Service after such notification
              constitutes acceptance of the revised Terms.
            </p>
          </section>

          {/* 10 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">10. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Texas, United States, without regard to
              conflict of law principles. Any disputes arising under these Terms shall be resolved in the
              courts of Texas.
            </p>
          </section>

          {/* 11 */}
          <section className="card space-y-3">
            <h2 className="text-lg font-semibold text-steel-100">11. Contact</h2>
            <p>
              For questions about these Terms, please contact us at:{" "}
              <a href={`mailto:${EMAIL}`} className="text-brand-400 hover:text-brand-300 underline">
                {EMAIL}
              </a>
            </p>
          </section>
        </div>

        {/* Footer copyright */}
        <div className="border-t border-steel-800 pt-6 text-center text-xs text-steel-600">
          © {COMPANY}. {WEBSITE}, {OWNER}-Owner. All rights reserved.
        </div>
      </main>
    </div>
  );
}
